### ISSUE TITLE
PTTime站点搜索出错

### ISSUE THREAD

**Issue by RocksonLee** [vertex-app/vertex#24]
**简述问题**
使用 聚合操作-种子搜索 报错

报错日志如下：

```
[04-05T10:50:59.502 (app/common/Site.js 169:14) PTTime 种子列表抓取失败 (疑似是 Cookie 失效, 或绕过 CloudFlare 5s 盾失效), 报错如下:
 TypeError: Cannot read property 'trim' of null
    at Site.searchTorrent (/app/vertex/app/libs/site/PTTime.js:47:97)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Site.search (/app/vertex/app/common/Site.js:165:22)
    at async Promise.all (index 0)
    at async SiteMod.search (/app/vertex/app/model/SiteMod.js:154:20)
    at async search (/app/vertex/app/controller/Site.js:112:17)
```

**简述环境**

Vertex 版本：

主版本：0.0.14.0 

编译版本：34e5a893be26

发布时间：2023-03-25 15:32:23

安装环境：hyper-v虚拟机下/debian11/docker

**截图**
![image](https://user-images.githubusercontent.com/57697347/229982223-a8b8adf2-7590-4377-9271-148de0533954.png)

**补充信息**

初步自检发现

/app/libs/site/PTTime.js 的第47行中
```
 _torrent.querySelector('.torrentname > tbody > tr .embedded br')).nextSibling 
```
为元素节点，返回 null 值，故导致报错

**Comment by vertex-app** [comment]
搜的什么

**Comment by RocksonLee** [comment]
刀剑神域

从 Windows 版邮件发送

发件人: lswl.in
发送时间: 2023年4月5日 12:45
收件人: vertex-app/vertex
抄送: RocksonLee; Author
主题: Re: [vertex-app/vertex] PTTime站点搜索出错 (Issue #24)

搜的什么
