### ISSUE TITLE
馒头依旧报错

### ISSUE THREAD

**Issue by Rainsheep** [vertex-app/vertex#49]
截图日志务必把版本: 885e0561d0b9/2024-03-23 00:24:33 带上

[03-24T08:18:00.042 (app/libs/rss.js 783:12) kp.m-team.cc 获取 Rss 报错 Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: e
    at error (/app/vertex/node_modules/sax/lib/sax.js:652:10)
    at strictFail (/app/vertex/node_modules/sax/lib/sax.js:678:7)
    at beginWhiteSpace (/app/vertex/node_modules/sax/lib/sax.js:952:7)
    at SAXParser.write (/app/vertex/node_modules/sax/lib/sax.js:1007:11)
    at Parser.exports.Parser.Parser.parseString (/app/vertex/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/app/vertex/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/app/vertex/node_modules/xml2js/lib/parser.js:369:19)
    at internal/util.js:340:30
    at new Promise (<anonymous>)
    at internal/util.js:339:12
    at _getTorrentsMTeam (/app/vertex/app/libs/rss.js:84:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.exports.getTorrents (/app/vertex/app/libs/rss.js:776:14)
    at async Promise.all (index 0)
    at async Rss.rss (/app/vertex/app/common/Rss.js:377:19)
[03-24T08:12:00.048 (app/libs/rss.js 783:12) kp.m-team.cc 获取 Rss 报错 Error: Non-whitespace before first tag.
Line: 0
Column: 1

**Comment by vertex-app** [comment]
有更多信息吗

**Comment by Rainsheep** [comment]
更新后好像没了，close
