### ISSUE TITLE
群晖安装部署报错

### ISSUE THREAD

**Issue by bits1125** [vertex-app/vertex#63]
**简述问题**
按照wiki指导在群晖中使用Container Manager进行部署，登录后提示初始化错误，以及其他目标不存在的错误。

**简述环境**
群晖Container Manager，dsm7.2，已安装node.js v18和v20

**截图**
![QQ截图20240810115107](https://github.com/user-attachments/assets/986f5ef8-0436-496e-a50e-67bc31f9a63d)
![QQ截图20240810115017](https://github.com/user-attachments/assets/05003c84-2948-45cd-b6bf-1c1cb219ba6e)

**补充信息**
[08-10T11:26:44.444 (app/controller/Server.js 115:14) ENOENT: no such file or directory, scandir '/app/vertex/app/data/server'
[08-10T11:26:44.443 (app/controller/Server.js 99:14) ENOENT: no such file or directory, scandir '/app/vertex/app/data/server'
[08-10T11:26:44.443 (fs.js 1048:3) Error: ENOENT: no such file or directory, scandir '/app/vertex/app/data/server'
    at Object.readdirSync (fs.js:1048:3)
    at Object.exports.listServer (/app/vertex/app/libs/util.js:295:20)
    at ServerMod.cpuUse (/app/vertex/app/model/ServerMod.js:70:25)
    at cpuUse (/app/vertex/app/controller/Server.js:109:33)
    at Layer.handle [as handle_request] (/app/vertex/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/vertex/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/app/vertex/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/app/vertex/node_modules/express/lib/router/layer.js:95:5)
    at /app/vertex/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/vertex/node_modules/express/lib/router/index.js:346:12)
    at next (/app/vertex/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/app/vertex/node_modules/express/lib/router/index.js:175:3)
    at router (/app/vertex/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/app/vertex/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/vertex/node_modules/express/lib/router/index.js:328:13)
    at /app/vertex/node_modules/express/lib/router/index.js:286:9 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/app/vertex/app/data/server'
}
[08-10T11:26:44.442 (fs.js 1048:3) Error: ENOENT: no such file or directory, scandir '/app/vertex/app/data/server'
    at Object.readdirSync (fs.js:1048:3)
    at Object.exports.listServer (/app/vertex/app/libs/util.js:295:20)
    at ServerMod.netSpeed (/app/vertex/app/model/ServerMod.js:52:25)
    at netSpeed (/app/vertex/app/controller/Server.js:93:33)
    at Layer.handle [as handle_request] (/app/vertex/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/vertex/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/app/vertex/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/app/vertex/node_modules/express/lib/router/layer.js:95:5)
    at /app/vertex/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/vertex/node_modules/express/lib/router/index.js:346:12)
    at next (/app/vertex/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/app/vertex/node_modules/express/lib/router/index.js:175:3)
    at router (/app/vertex/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/app/vertex/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/vertex/node_modules/express/lib/router/index.js:328:13)
    at /app/vertex/node_modules/express/lib/router/index.js:286:9 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/app/vertex/app/data/server'
}
[08-10T11:26:44.441 (fs.js 1048:3) Error: ENOENT: no such file or directory, scandir '/app/vertex/app/data/server'
    at Object.readdirSync (fs.js:1048:3)
    at Object.exports.listServer (/app/vertex/app/libs/util.js:295:20)
    at ServerMod.list (/app/vertex/app/model/ServerMod.js:35:29)
    at list (/app/vertex/app/controller/Server.js:60:27)
    at Layer.handle [as handle_request] (/app/vertex/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/vertex/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/app/vertex/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/app/vertex/node_modules/express/lib/router/layer.js:95:5)
    at /app/vertex/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/vertex/node_modules/express/lib/router/index.js:346:12)
    at next (/app/vertex/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/app/vertex/node_modules/express/lib/router/index.js:175:3)
    at router (/app/vertex/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/app/vertex/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/vertex/node_modules/express/lib/router/index.js:328:13)
    at /app/vertex/node_modules/express/lib/router/index.js:286:9 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/app/vertex/app/data/server'
}
[08-10T11:25:02.056 (fs.js 1048:3) 初始化任务报错
 Error: ENOENT: no such file or directory, scandir '/app/vertex/app/data/push'
    at Object.readdirSync (fs.js:1048:3)
    at Object.exports.listPush (/app/vertex/app/libs/util.js:273:20)
    at initPush (/app/vertex/app/app.js:30:28)
    at init (/app/vertex/app/app.js:111:3)
    at /app/vertex/app/app.js:158:5
    at Object.<anonymous> (/app/vertex/app/app.js:185:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/app/vertex/app/data/push'
}

**Comment by vertex-app** [comment]
文件夹权限

**Comment by bits1125** [comment]
> 文件夹权限

看了 docker/vertex文件夹是root权限 试了PGID=101 PUID=1026或者PGID=0 PUID=0 依然报错

**Comment by bits1125** [comment]
> 文件夹权限

文件夹有的可以自动创建，有的就不行，比如上面报错的那些，我看目录里就没有。
![QQ截图20240810153340](https://github.com/user-attachments/assets/a73ee530-8305-4e82-914b-87d6e928fbeb)
![QQ截图20240810153405](https://github.com/user-attachments/assets/8fc669ee-cb03-4936-89be-3050beb6a65b)

**Comment by vertex-app** [comment]
文件夹全删了重新装，不要加 PUID 和 PGID

**Comment by bits1125** [comment]
> 文件夹全删了重新装，不要加 PUID 和 PGID

好的 我再试试

**Comment by bits1125** [comment]
> 文件夹全删了重新装，不要加 PUID 和 PGID

全部都删除 重新部署好了
