### ISSUE TITLE
bug: 硬盘空间不足时更改 rss 规则会导致脏数据

### ISSUE THREAD

**Issue by yxlimo** [vertex-app/vertex#78]
环境： 云飞的 NC 盒子

种子很多的时候更改 rss 规则，会报错 `database or disk is full`
之后访问 rss 规则相关的所有接口后端后端都会返回 `{"success":false,"message":"Unexpected end of JSON input"}`

```
[12-13T18:18:00.255 (app/libs/util.js 53:26) 07.我堡（需开V）🚩 SqliteError: database or disk is full
    at Object.exports.runRecord (/app/vertex/app/libs/util.js:53:26)
    at Rss._pushTorrent (/app/vertex/app/common/Rss.js:267:20)
    at Rss.rss (/app/vertex/app/common/Rss.js:449:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Task.execution (/app/vertex/app/comm[12-13T18:17:00.192 (app/libs/util.js 53:26) 07.我堡（需开V）🚩 SqliteError: database or disk is full
    at Object.exports.runRecord (/app/vertex/app/libs/util.js:53:26)
    at Rss._pushTorrent (/app/vertex/app/common/Rss.js:267:20)
    at Rss.rss (/app/vertex/app/common/Rss.js:449:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Task.execution (/app/vertex/app/common/Rss.js:56:65) {
  code: 'SQLITE_FULL'
}
[12-13T18:16:00.650 (app/libs/util.js 53:26) 07.我堡（需开V）🚩 SqliteError: database or disk is full
    at Object.exports.runRecord (/app/vertex/app/libs/util.js:53:26)
    at Rss._pushTorrent (/app/vertex/app/common/Rss.js:267:20)
    at Rss.rss (/app/vertex/app/common/Rss.js:449:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Task.execution (/app/vertex/app/common/Rss.js:56:65) {
  code: 'SQLITE_FULL'
}
[12-13T18:15:00.637 (app/libs/util.js 53:26) 07.我堡（需开V）🚩 SqliteError: database or disk is full
    at Object.exports.runRecord (/app/vertex/app/libs/util.js:53:26)
    at Rss._pushTorrent (/app/vertex/app/common/Rss.js:267:20)
    at Rss.rss (/app/vertex/app/common/Rss.js:449:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Task.execution (/app/vertex/app/common/Rss.js:56:65) {
  code: 'SQLITE_FULL'
}
[12-13T18:14:00.271 (app/libs/util.js 53:26) 07.我堡（需开V）🚩 SqliteError: database or disk is full
    at Object.exports.runRecord (/app/vertex/app/libs/util.js:53:26)
    at Rss._pushTorrent (/app/vertex/app/common/Rss.js:267:20)
    at Rss.rss (/app/vertex/app/common/Rss.js:449:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Task.execution (/app/vertex/app/common/Rss.js:56:65) {
  code: 'SQLITE_FULL'
}
[12-13T18:13:00.383 (app/libs/util.js 53:26) 07.我堡（需开V）🚩 SqliteError: database or disk is full
    at Object.exports.runRecord (/app/vertex/app/libs/util.js:53:26)
    at Rss._pushTorrent (/app/vertex/app/common/Rss.js:267:20)
    at Rss.rss (/app/vertex/app/common/Rss.js:449:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Task.execution (/app/vertex/app/common/Rss.js:56:65) {
  code: 'SQLITE_FULL'
}
[12-13T18:12:00.442 (app/libs/util.js 53:26) 07.我堡（需开V）🚩 SqliteError: database or disk is full
    at Object.exports.runRecord (/app/vertex/app/libs/util.js:53:26)
    at Rss._pushTorrent (/app/vertex/app/common/Rss.js:267:20)
    at Rss.rss (/app/vertex/app/common/Rss.js:449:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Task.execution (/app/vertex/app/common/Rss.js:56:65) {
  code: 'SQLITE_FULL'
}
```

**Comment by vertex-app** [comment]
磁盘满了是会这样，找到对应的空 json 文件删除重启
